import psycopg2
import psycopg2.extras
import psycopg2.extensions
from typing import Dict, List, Any, Optional
import json
import time
import re


class PostgresDataClient:
    """
    A client for connecting to PostgreSQL databases to:
    1. Introspect schema (tables, columns, relationships)
    2. Execute SQL queries generated by the Text2SQL system
    
    This replaces the proprietary Denodo API with direct PostgreSQL access.
    """
    
    def __init__(self, connection_string: str):
        """
        Initialize with a PostgreSQL connection string.
        
        Format: postgresql://user:password@host:port/database
        """
        self.connection_string = connection_string
        self._test_connection()
    
    def _test_connection(self):
        """Test that we can connect to the database."""
        try:
            conn = psycopg2.connect(self.connection_string)
            conn.close()
            print("✅ Successfully connected to PostgreSQL database")
        except Exception as e:
            print(f"❌ Failed to connect to database: {e}")
            raise
    
    def get_schema_metadata(self, schema_name: str = 'public') -> Dict[str, Any]:
        """
        Get comprehensive schema metadata for the Text2SQL system.
        
        Fixed version with proper schema-qualified joins and better error handling.
        """
        metadata = {
            "database_type": "postgresql",
            "schema_name": schema_name,
            "tables": [],
            "relationships": [],
            "statistics": {}
        }
        
        conn = None
        try:
            conn = psycopg2.connect(self.connection_string)
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            
            # 1. Get all tables with proper schema-qualified comments
            cursor.execute("""
                SELECT 
                    t.table_name,
                    obj_description(c.oid, 'pg_class') as table_comment
                FROM information_schema.tables t
                LEFT JOIN pg_class c ON c.relname = t.table_name
                LEFT JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = t.table_schema
                WHERE t.table_schema = %s 
                AND t.table_type = 'BASE TABLE'
                ORDER BY t.table_name
            """, (schema_name,))
            
            tables = cursor.fetchall()
            
            for table in tables:
                table_info = {
                    "table_name": table['table_name'],
                    "description": table['table_comment'] or "",
                    "columns": [],
                    "primary_keys": [],
                    "foreign_keys": [],
                    "indexes": []
                }
                
                # 2. Get columns with proper schema-qualified comments
                cursor.execute("""
                    SELECT 
                        c.column_name,
                        c.data_type,
                        c.character_maximum_length,
                        c.is_nullable,
                        c.column_default,
                        col_description(pgc.oid, c.ordinal_position) as column_comment
                    FROM information_schema.columns c
                    LEFT JOIN pg_class pgc ON pgc.relname = c.table_name
                    LEFT JOIN pg_namespace pgn ON pgn.oid = pgc.relnamespace AND pgn.nspname = c.table_schema
                    WHERE c.table_schema = %s 
                    AND c.table_name = %s
                    ORDER BY c.ordinal_position
                """, (schema_name, table['table_name']))
                
                columns = cursor.fetchall()
                
                for col in columns:
                    column_info = {
                        "column_name": col['column_name'],
                        "data_type": col['data_type'],
                        "max_length": col['character_maximum_length'],
                        "nullable": col['is_nullable'] == 'YES',
                        "default": col['column_default'],
                        "description": col['column_comment'] or ""
                    }
                    
                    # Simplify data types for LLM understanding
                    column_info['simple_type'] = self._simplify_data_type(col['data_type'])
                    table_info['columns'].append(column_info)
                
                # 3. Get primary keys with safer approach
                cursor.execute("""
                    SELECT a.attname as column_name
                    FROM pg_index i
                    JOIN pg_attribute a ON a.attrelid = i.indrelid
                        AND a.attnum = ANY(i.indkey)
                    JOIN pg_class c ON c.oid = i.indrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relname = %s
                    AND n.nspname = %s
                    AND i.indisprimary
                """, (table['table_name'], schema_name))
                
                pk_columns = cursor.fetchall()
                table_info['primary_keys'] = [pk['column_name'] for pk in pk_columns]
                
                # 4. Get foreign keys with better error handling
                cursor.execute("""
                    SELECT
                        kcu.column_name,
                        ccu.table_name AS foreign_table_name,
                        ccu.column_name AS foreign_column_name
                    FROM information_schema.table_constraints AS tc
                    JOIN information_schema.key_column_usage AS kcu
                        ON tc.constraint_name = kcu.constraint_name
                        AND tc.table_schema = kcu.table_schema
                    JOIN information_schema.constraint_column_usage AS ccu
                        ON ccu.constraint_name = tc.constraint_name
                        AND ccu.table_schema = tc.table_schema
                    WHERE tc.constraint_type = 'FOREIGN KEY'
                    AND tc.table_schema = %s
                    AND tc.table_name = %s
                """, (schema_name, table['table_name']))
                
                foreign_keys = cursor.fetchall()
                
                for fk in foreign_keys:
                    fk_info = {
                        "column": fk['column_name'],
                        "references_table": fk['foreign_table_name'],
                        "references_column": fk['foreign_column_name']
                    }
                    table_info['foreign_keys'].append(fk_info)
                    
                    # Also add to relationships for easier access
                    metadata['relationships'].append({
                        "from_table": table['table_name'],
                        "from_column": fk['column_name'],
                        "to_table": fk['foreign_table_name'],
                        "to_column": fk['foreign_column_name'],
                        "relationship_type": "foreign_key"
                    })
                
                # 5. Get indexes with schema qualification
                cursor.execute("""
                    SELECT
                        i.relname as indexname,
                        pg_get_indexdef(i.oid) as indexdef
                    FROM pg_class i
                    JOIN pg_index ix ON i.oid = ix.indexrelid
                    JOIN pg_class t ON ix.indrelid = t.oid
                    JOIN pg_namespace n ON t.relnamespace = n.oid
                    WHERE t.relname = %s
                    AND n.nspname = %s
                    AND i.relname NOT LIKE '%%_pkey'
                """, (table['table_name'], schema_name))
                
                indexes = cursor.fetchall()
                table_info['indexes'] = [
                    {
                        "index_name": idx['indexname'],
                        "definition": idx['indexdef']
                    }
                    for idx in indexes
                ]
                
                metadata['tables'].append(table_info)
            
            # 6. Get statistics with error handling
            try:
                cursor.execute("""
                    SELECT COUNT(*) as table_count
                    FROM information_schema.tables
                    WHERE table_schema = %s AND table_type = 'BASE TABLE'
                """, (schema_name,))
                
                stats = cursor.fetchone()
                metadata['statistics']['table_count'] = stats['table_count'] if stats else 0
                
                # Count total columns
                total_columns = sum(len(t['columns']) for t in metadata['tables'])
                metadata['statistics']['total_columns'] = total_columns
                
                # Count relationships
                metadata['statistics']['relationship_count'] = len(metadata['relationships'])
                
            except Exception as e:
                print(f"Warning: Could not retrieve statistics: {e}")
                metadata['statistics'] = {"error": str(e)}
            
            cursor.close()
            
            return metadata
            
        except Exception as e:
            print(f"Error getting schema metadata: {e}")
            if conn:
                conn.rollback()
            raise
        finally:
            if conn:
                conn.close()
    
    def _simplify_data_type(self, data_type: str) -> str:
        """
        Simplify PostgreSQL data types for LLM understanding.
        """
        type_mapping = {
            'character varying': 'text',
            'varchar': 'text',
            'character': 'text',
            'char': 'text',
            'text': 'text',
            'integer': 'number',
            'bigint': 'number',
            'smallint': 'number',
            'numeric': 'decimal',
            'decimal': 'decimal',
            'real': 'decimal',
            'double precision': 'decimal',
            'money': 'decimal',
            'boolean': 'boolean',
            'timestamp': 'datetime',
            'timestamp without time zone': 'datetime',
            'timestamp with time zone': 'datetime',
            'date': 'datetime',
            'time': 'datetime',
            'uuid': 'text',
            'json': 'json',
            'jsonb': 'json'
        }
        
        return type_mapping.get(data_type.lower(), data_type)
    
    def execute_query(self, sql_query: str, params: Optional[tuple] = None, timeout: int = 30) -> Dict[str, Any]:
        """
        Execute a SQL query and return results with improved security and error handling.
        """
        result = {
            "success": False,
            "data": [],
            "affected_rows": 0,
            "columns": [],
            "error": None,
            "execution_time": 0
        }
        
        # Basic query validation
        if not self._is_safe_query(sql_query):
            result['error'] = "Query contains potentially unsafe operations"
            return result
        
        conn = None
        start_time = time.time()
        
        try:
            conn = psycopg2.connect(self.connection_string)
            # Set query timeout
            conn.cursor().execute(f"SET statement_timeout = {timeout * 1000}")
            
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
            
            # Execute the query
            if params:
                cursor.execute(sql_query, params)
            else:
                cursor.execute(sql_query)
            
            # Check if it's a SELECT query
            if cursor.description:
                # It's a SELECT - fetch results
                result['columns'] = [desc[0] for desc in cursor.description]
                rows = cursor.fetchall()
                
                # Convert to list of dicts with proper serialization
                result['data'] = [dict(row) for row in rows]
                result['affected_rows'] = len(result['data'])
            else:
                # It's an INSERT/UPDATE/DELETE
                result['affected_rows'] = cursor.rowcount
                conn.commit()
            
            result['success'] = True
            result['execution_time'] = time.time() - start_time
            
            cursor.close()
            
        except psycopg2.Error as e:
            print(f"PostgreSQL error executing query: {e}")
            result['error'] = f"Database error: {str(e)}"
            if conn:
                conn.rollback()
        except Exception as e:
            print(f"Error executing query: {e}")
            result['error'] = str(e)
            if conn:
                conn.rollback()
        finally:
            if conn:
                conn.close()
        
        return result
    
    def _is_safe_query(self, query: str) -> bool:
        """
        Basic query validation to prevent dangerous operations.
        
        In production, you'd want more sophisticated validation.
        """
        query_upper = query.upper().strip()
        
        # List of dangerous operations
        dangerous_operations = [
            'DROP', 'DELETE', 'UPDATE', 'INSERT', 'CREATE', 'ALTER',
            'TRUNCATE', 'GRANT', 'REVOKE', 'COPY', '\\', 'EXEC',
            'EXECUTE', 'CALL'
        ]
        
        # Allow SELECT, WITH (for CTEs), and EXPLAIN
        allowed_starts = ('SELECT', 'WITH', 'EXPLAIN')
        if not query_upper.startswith(allowed_starts):
            return False
            
        # Check for dangerous operations within the query
        # Use word boundaries to avoid false positives
        import re
        for operation in dangerous_operations:
            # Look for the operation as a whole word, not part of another word
            pattern = r'\b' + re.escape(operation) + r'\b'
            if re.search(pattern, query_upper):
                return False
                
        return True
    
    def test_connection_with_query(self) -> bool:
        """
        Test the connection with a simple query.
        """
        try:
            result = self.execute_query("SELECT 1 as test")
            return result['success'] and result['data'][0]['test'] == 1
        except Exception:
            return False
    
    def get_sample_data(self, table_name: str, limit: int = 5, schema_name: str = 'public') -> List[Dict]:
        """
        Get sample data from a table with proper schema qualification.
        """
        try:
            # Use format() with proper identifier quoting for safety
            # This avoids psycopg2 version compatibility issues
            query = 'SELECT * FROM "{}"."{}" LIMIT %s'.format(
                schema_name.replace('"', '""'),  # Escape any quotes in schema name
                table_name.replace('"', '""')    # Escape any quotes in table name
            )
            
            result = self.execute_query(query, (limit,))
            
            if result['success']:
                return result['data']
            return []
        except Exception as e:
            print(f"Error getting sample data: {e}")
            return []
    
    def explain_query(self, sql_query: str) -> Dict[str, Any]:
        """
        Get query execution plan with better error handling.
        """
        if not self._is_safe_query(sql_query):
            return {"error": "Query not safe for explanation"}
        
        explain_query = f"EXPLAIN (FORMAT JSON, ANALYZE, BUFFERS) {sql_query}"
        result = self.execute_query(explain_query)
        
        if result['success'] and result['data']:
            return result['data'][0]
        return {"error": result.get('error', 'Unknown error')}
    
    def format_schema_for_llm(self, schema_name: str = 'public') -> str:
        """
        Format schema metadata in a way that's easy for LLMs to understand.
        """
        try:
            metadata = self.get_schema_metadata(schema_name)
        except Exception as e:
            return f"Error retrieving schema: {str(e)}"
        
        output = []
        output.append(f"Database Schema ({metadata['schema_name']}):")
        output.append(f"Total tables: {metadata['statistics'].get('table_count', 'unknown')}")
        output.append("")
        
        for table in metadata['tables']:
            output.append(f"Table: {table['table_name']}")
            if table['description']:
                output.append(f"  Description: {table['description']}")
            
            # Group columns by type for better readability
            output.append("  Columns:")
            for col in table['columns']:
                nullable = "NULL" if col['nullable'] else "NOT NULL"
                type_info = col['simple_type']
                if col['max_length']:
                    type_info += f"({col['max_length']})"
                
                output.append(f"    - {col['column_name']}: {type_info} {nullable}")
                if col['description']:
                    output.append(f"      Description: {col['description']}")
            
            if table['primary_keys']:
                output.append(f"  Primary Key: {', '.join(table['primary_keys'])}")
            
            if table['foreign_keys']:
                output.append("  Foreign Keys:")
                for fk in table['foreign_keys']:
                    output.append(f"    - {fk['column']} -> {fk['references_table']}.{fk['references_column']}")
            
            output.append("")
        
        if metadata['relationships']:
            output.append("Key Relationships:")
            for rel in metadata['relationships']:
                output.append(f"  {rel['from_table']}.{rel['from_column']} -> {rel['to_table']}.{rel['to_column']}")
        
        return "\n".join(output)
    
    def get_database_info(self) -> Dict[str, Any]:
        """
        Get basic database information for debugging and integration.
        """
        try:
            conn = psycopg2.connect(self.connection_string)
            cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

            # Get database name, version, and other info
            cursor.execute("SELECT current_database(), version(), current_user;")
            db_info = cursor.fetchone()
            
            # Check if pgvector is available
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_extension WHERE extname = 'vector'
                ) as has_pgvector;
            """)
            pgvector_info = cursor.fetchone()
            
            cursor.close()
            conn.close()
            
            if db_info is not None and pgvector_info is not None:
                return {
                    "database_name": db_info[0],
                    "version": db_info[1],
                    "current_user": db_info[2],
                    "has_pgvector": pgvector_info['has_pgvector'],
                    "connection_status": "active"
                }
            else:
                return {
                    "error": "Could not retrieve database info.",
                    "connection_status": "failed"
                }
        except Exception as e:
            return {
                "error": str(e),
                "connection_status": "failed"
            }
    
    def validate_memory_compatibility(self) -> Dict[str, Any]:
        """
        Check if the database is compatible with the memory system.
        This is useful when integrating with the MemoryAgent.
        """
        try:
            conn = psycopg2.connect(self.connection_string)
            cursor = conn.cursor()

            compatibility = {
                "compatible": True,
                "issues": [],
                "recommendations": []
            }

            # Check PostgreSQL version (should be minimum 11+ for pgvector)
            cursor.execute("SELECT version();")
            version_row = cursor.fetchone()
            if version_row is not None:
                version_info = version_row[0]
            else:
                compatibility["compatible"] = False
                compatibility["issues"].append("Could not retrieve PostgreSQL version.")
                version_info = None

            # Extract major version number
            version_match = re.search(r'PostgreSQL (\d+)', version_info) if version_info is not None else None
            if version_match:
                major_version = int(version_match.group(1))
                if major_version < 11:
                    compatibility["compatible"] = False
                    compatibility["issues"].append(f"PostgreSQL version {major_version} is too old. Need 11+")
            
            # Check if pgvector extension exists
            cursor.execute("""
                SELECT EXISTS (
                           SELECT 1 FROM pg_available_extension WHERE name = 'vector'
                ) as vector_available;
            """)
            vector_avail = cursor.fetchone()
            if vector_avail is not None:
                vector_available = vector_avail[0]

            if not vector_available:
                compatibility["compatible"] = False
                compatibility["issues"].append("pgvector extension is not available.")
                compatibility['recommendations'].append("Install pgvector extension.")

            # Check if pgvector is enabled.
            cursor.execute("""
                    SELECT EXISTS (
                           SELECT 1 FROM pg_extension WHERE extname = 'vector'
                        ) as vector_enabled;
                """)
            vector_enable = cursor.fetchone()
            if vector_enable is not None:
                vector_enabled = vector_enable[0]

            if vector_available and not vector_enabled:
                compatibility["recommendations"].append("Enable pgvector with: CREATE EXTENSION vector;")

            cursor.close()
            conn.close()

            return compatibility
        
        except Exception as e:
            return {
                "compatible": False,
                "error": str(e),
                "issues": ["Could not connect to database."]
            }